// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'types.freezed.dart';

@freezed
class Backup with _$Backup {
  const factory Backup({
    required String name,
    String? seed,
    required int index,
    String? sk,
    required String fvk,
    required String uvk,
    String? tsk,
    required bool saved,
  }) = _Backup;
}

@freezed
class BlockHeight with _$BlockHeight {
  const factory BlockHeight({
    required int height,
    required int timestamp,
  }) = _BlockHeight;
}

@freezed
class Contact with _$Contact {
  const factory Contact({
    required int id,
    required String name,
    required String address,
  }) = _Contact;
}

@freezed
class Fee with _$Fee {
  const factory Fee({
    required int scheme,
    required BigInt fee,
  }) = _Fee;
}

class ParsedMemo {
  final bool reply;
  final String subject;
  final String memo;

  const ParsedMemo({
    required this.reply,
    required this.subject,
    required this.memo,
  });

  @override
  int get hashCode => reply.hashCode ^ subject.hashCode ^ memo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ParsedMemo &&
          runtimeType == other.runtimeType &&
          reply == other.reply &&
          subject == other.subject &&
          memo == other.memo;
}

class PaymentURI {
  final String address;
  final BigInt amount;
  final String memo;

  const PaymentURI({
    required this.address,
    required this.amount,
    required this.memo,
  });

  @override
  int get hashCode => address.hashCode ^ amount.hashCode ^ memo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PaymentURI &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          amount == other.amount &&
          memo == other.memo;
}

@freezed
class PoolBalance with _$PoolBalance {
  const factory PoolBalance({
    required BigInt transparent,
    required BigInt sapling,
    required BigInt orchard,
  }) = _PoolBalance;
}

@freezed
class Progress with _$Progress {
  const factory Progress({
    required int timestamp,
    required int trialDecryptions,
    required int height,
    required int downloaded,
  }) = _Progress;
}

@freezed
class Quote with _$Quote {
  const factory Quote({
    required int timestamp,
    required double price,
  }) = _Quote;
}

class SendContext {
  final String address;
  final int pools;
  final BigInt amount;
  final bool receiverFee;
  final ParsedMemo memo;

  const SendContext({
    required this.address,
    required this.pools,
    required this.amount,
    required this.receiverFee,
    required this.memo,
  });

  @override
  int get hashCode =>
      address.hashCode ^
      pools.hashCode ^
      amount.hashCode ^
      receiverFee.hashCode ^
      memo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SendContext &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          pools == other.pools &&
          amount == other.amount &&
          receiverFee == other.receiverFee &&
          memo == other.memo;
}

@freezed
class ShieldedNote with _$ShieldedNote {
  const factory ShieldedNote({
    required int id,
    required int height,
    required BigInt value,
    required int timestamp,
    required bool orchard,
    required bool excluded,
    required bool spent,
  }) = _ShieldedNote;
}

@freezed
class Spending with _$Spending {
  const factory Spending({
    required String recipient,
    required PlatformInt64 amount,
  }) = _Spending;
}

@freezed
class TxMemo with _$TxMemo {
  const factory TxMemo({
    required int direction,
    required String address,
    required String memo,
  }) = _TxMemo;
}

@freezed
class TxTimeValue with _$TxTimeValue {
  const factory TxTimeValue({
    required int timestamp,
    required PlatformInt64 value,
  }) = _TxTimeValue;
}
